### ISSUE TITLE
verify credentials fails

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/petstore-component-java#10]
The recently updated version of the component (6.02.2020) gives an error on verify credentials part.

```
Starting your Docker container ...
Starting slug download ...
Starting application in apprunner...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Successfully downloaded and extracted slug file
08:32:32,633 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:32:33,296 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:32:33,297 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:32:32,633 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-2.1.2.jar!/logback.xml]
08:32:32,786 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:32:32,859 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
08:32:32,633 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:32:32,801 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:32:33,297 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:32:32,650 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@369f73a2 - URL [jar:file:/home/apprunner/build/elasticio/dependencies/sailor-jvm-2.1.2.jar!/logback.xml] is not of type file
08:32:32,806 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:32:33,302 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1f28c152 - Registering current configuration as safe fallback point
(no message)
Starting execution of verifyCredentials
Component descriptor from classpath: /component.json
(no message)
Caused by: java.lang.IllegalStateException: Component descriptor /component.json is not found in the classpath
at io.elastic.sailor.Service.main(Service.java:58)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
at io.elastic.sailor.Service.getServiceInstanceAndExecute(Service.java:79)
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error injecting constructor, java.lang.IllegalStateException: Component descriptor /component.json is not found in the classpath
for the 1st parameter of io.elastic.sailor.Service.<init>(Service.java:31)
while locating io.elastic.sailor.Service
(no message)
at io.elastic.sailor.ComponentDescriptorResolver.loadComponentJson(ComponentDescriptorResolver.java:37)
at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
while locating io.elastic.sailor.ComponentDescriptorResolver
at io.elastic.sailor.ComponentDescriptorResolver.<init>(ComponentDescriptorResolver.java:25)
1 error
at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
at io.elastic.sailor.Service.createServiceInstanceAndExecute(Service.java:73)
at io.elastic.sailor.ComponentDescriptorResolver.<init>(ComponentDescriptorResolver.java:26)
at io.elastic.sailor.ComponentDescriptorResolver$$FastClassByGuice$$4dbcba79.newInstance(<generated>)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
... 4 more
at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
[INFO  tini (1)] Main child exited normally (with status '1')
```

**Comment by khanzadyan** [comment]
@drobiazko FYI

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/petstore-component-java/releases/tag/1.0.7
