### ISSUE TITLE
Uses an outdated gradle version

### ISSUE THREAD

**Issue by dagnelies** [elasticio/petstore-component-java#8]
Following warning pops up during the build:

> Support for builds using Gradle older than 2.6 was deprecated and will be removed in 5.0. You are currently using Gradle version 2.0. You should upgrade your Gradle build to use Gradle 2.6 or later.

**Comment by dagnelies** [comment]
Gradle 2.0 is now problematic because such old version are poorly (if at all) supported by most IDEs. We are now at gradle 5+.

I tried simply upgrading the gradle wrapper dependency, but this lead to other issues down the pipeline. When starting a flow in elastic.io, it leads to:

	Starting your Docker container ...
	Starting application in apprunner...
	[INFO  tini (1)] Spawned child process '/run.sh' with pid '8'
	Starting slug download ...
	Successfully downloaded and extracted slug file
	INFO  i.e.s.Service T: - Starting execution of verifyCredentials
	INFO  i.e.s.ComponentDescriptorResolver T: - Component descriptor from classpath: /component.json
	Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
	(no message)
	1) Error injecting constructor, java.lang.IllegalStateException: Component descriptor /component.json is not found in the classpath
	(no message)
	at io.elastic.sailor.Service.createServiceInstanceAndExecute(Service.java:73)
	Caused by: java.lang.IllegalStateException: Component descriptor /component.json is not found in the classpath
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
